#!/usr/bin/env python3
"""Generate or check the NBFM complex channel FIR coefficients.

Requires NumPy for this offline design tool; the receiver has no NumPy dependency.
Run without arguments to regenerate src/nbfm_channel_coeffs.h. Run with --check
to verify that the checked-in header matches the design and report its response.
"""

import argparse
from pathlib import Path

import numpy as np


SAMPLE_RATE_HZ = 200_000
PASSBAND_HZ = 6_000
STOPBAND_HZ = 9_000
CUTOFF_HZ = 7_500
TAPS = 321
KAISER_BETA = 7.5
FFT_SIZE = 1 << 20
HEADER_PATH = Path(__file__).resolve().parents[1] / "src" / "nbfm_channel_coeffs.h"


def coefficients():
    """Return symmetric, DC-normalized coefficients rounded to C float."""
    position = np.arange(TAPS, dtype=np.float64) - (TAPS - 1) / 2
    cutoff = 2 * CUTOFF_HZ / SAMPLE_RATE_HZ
    taps = cutoff * np.sinc(cutoff * position) * np.kaiser(TAPS, KAISER_BETA)
    taps /= np.sum(taps)
    return taps.astype(np.float32)


def c_float(value):
    # Nine significant decimal digits round-trip any finite IEEE float32.
    literal = format(float(value), ".9g")
    if "." not in literal and "e" not in literal:
        literal += ".0"
    return literal + "f"


def header_text(taps):
    rows = [
        "    " + ", ".join(c_float(value) for value in taps[start:start + 4]) + ","
        for start in range(0, TAPS, 4)
    ]
    return "\n".join([
        "#pragma once",
        "",
        "// Generated by tools/design_nbfm_channel_filter.py; do not edit by hand.",
        "// Complex low-pass FIR at 200 kS/s, decimated by four after filtering.",
        "// Passband +/-6 kHz, stopband from +/-9 kHz; Kaiser beta 7.5.",
        "// Windowed-sinc cutoff 7.5 kHz; unity DC gain, symmetric 321 taps.",
        "#define NBFM_CHANNEL_TAPS 321",
        "",
        "static const float nbfm_channel_coeffs[NBFM_CHANNEL_TAPS] = {",
        *rows,
        "};",
        "",
    ])


def cic_gain(frequency_hz, rf_rate_hz):
    # Three cascaded RF-rate boxcars of length RF rate / 200 kS/s.
    return np.abs(np.sinc(frequency_hz / SAMPLE_RATE_HZ) /
                  np.sinc(frequency_hz / rf_rate_hz)) ** 3


def report_response(taps, csv_path=None):
    # FFT in double precision measures the actual rounded float coefficients.
    response = np.abs(np.fft.rfft(taps.astype(np.float64), FFT_SIZE))
    frequency = np.fft.rfftfreq(FFT_SIZE, 1 / SAMPLE_RATE_HZ)
    response_db = 20 * np.log10(np.maximum(response, np.finfo(float).tiny))
    passband = response_db[frequency <= PASSBAND_HZ]
    stopband = response_db[frequency >= STOPBAND_HZ]
    noise_bandwidth = SAMPLE_RATE_HZ * np.sum(taps.astype(np.float64) ** 2)
    print(f"FIR: {TAPS} taps, Kaiser beta {KAISER_BETA}, "
          f"cutoff {CUTOFF_HZ} Hz, sample rate {SAMPLE_RATE_HZ} S/s")
    print(f"Float coefficient sum: {np.sum(taps.astype(np.float64)):.10f}")
    print(f"Response grid: {frequency[1]:.6f} Hz")
    print(f"Passband through +/-{PASSBAND_HZ} Hz: "
          f"{passband.min():.6f} to {passband.max():.6f} dB")
    print(f"Worst stopband from +/-{STOPBAND_HZ} Hz: {stopband.max():.3f} dB")
    for offset in (9_000, 12_500):
        print(f"Response at +/-{offset} Hz: "
              f"{np.interp(offset, frequency, response_db):.3f} dB")
    print(f"FIR group delay: {(TAPS - 1) / (2 * SAMPLE_RATE_HZ) * 1e3:.3f} ms")
    print(f"FIR two-sided equivalent noise bandwidth: {noise_bandwidth:.2f} Hz")
    for rf_rate in (1_000_000, 2_000_000, 4_000_000):
        decimation = rf_rate // SAMPLE_RATE_HZ
        passband_droop = 20 * np.log10(cic_gain(PASSBAND_HZ, rf_rate))
        alias_edges = [
            band * SAMPLE_RATE_HZ + edge
            for band in range(1, rf_rate // (2 * SAMPLE_RATE_HZ) + 1)
            for edge in (-PASSBAND_HZ, PASSBAND_HZ)
            if band * SAMPLE_RATE_HZ + edge < rf_rate / 2
        ]
        alias_gain = max(cic_gain(value, rf_rate) for value in alias_edges)
        delay_ms = 3 * (decimation - 1) / (2 * rf_rate) * 1e3
        print(f"CIC3 at {rf_rate:,} S/s (D={decimation}): "
              f"6 kHz droop {passband_droop:.5f} dB, "
              f"worst alias-band edge into +/-6 kHz "
              f"{20 * np.log10(alias_gain):.2f} dB, "
              f"combined group delay "
              f"{delay_ms + (TAPS - 1) / (2 * SAMPLE_RATE_HZ) * 1e3:.6f} ms")
    if csv_path:
        np.savetxt(csv_path, np.column_stack((frequency, response_db)),
                   delimiter=",", header="frequency_hz,response_db", comments="")
        print(f"Response CSV written to {csv_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the checked-in header without modifying it")
    parser.add_argument("--csv", type=Path,
                        help="optionally write the dense FIR response as CSV")
    args = parser.parse_args()
    taps = coefficients()
    generated = header_text(taps)
    if args.check:
        if not HEADER_PATH.exists() or HEADER_PATH.read_text() != generated:
            parser.exit(1, f"Coefficient header differs: {HEADER_PATH}\n"
                        "Run this script without --check to regenerate it.\n")
        print(f"Coefficient header matches: {HEADER_PATH}")
    else:
        HEADER_PATH.write_text(generated)
        print(f"Coefficient header written to {HEADER_PATH}")
    report_response(taps, args.csv)


if __name__ == "__main__":
    main()
